version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: thenecromancerx/docker-python-serverless
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    parameters:
      distros:
        default: "slim alpine buster stretch"
        type: string
      python_versions:
        default: "3.6 3.7 3.8"
        type: string
      node_versions:
        default: "10 12 14 15"
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Nested Loop
          command: |
            mkdir images
            for distro in <<parameters.distros>>; do
              if [[ $distro = 'buster' ]]
              then
                docker build -t $IMAGE_NAME:python3.7-nodejs15-buster --build-arg NODE=python3.7-nodejs15 . -f Dockerfile
                docker save -o images/python3.7-nodejs15-buster.tar $IMAGE_NAME:python3.7-nodejs15-buster
              elif [[ $distro = 'alpine' ]]
              then
                docker build -t $IMAGE_NAME:python3.7-nodejs15-alpine --build-arg NODE=python3.7-nodejs15-alpine . -f alpine.Dockerfile
                docker save -o images/python3.7-nodejs15-alpine.tar $IMAGE_NAME:python3.7-nodejs15-alpine
              else
                docker build -t $IMAGE_NAME:python3.7-nodejs15-$distro --build-arg NODE=python3.7-$distro . -f Dockerfile
                docker save -o images/python3.7-nodejs15-$distro.tar $IMAGE_NAME:python3.7-nodejs15-$distro
              fi
            done
      - persist_to_workspace:
          root: .
          paths:
            - ./images
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            # IMAGE_TAG=${CIRCLE_TAG/v/''}
            # docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            # docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
  # build-tags:
  #   jobs:
  #     - build:
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/
  #     - publish-tag:
  #         requires:
  #           - build
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/
